const posts = [
  {
    id: "01",
    title: "Sand home",
    location: "Valencia",
    images: ["https://res.cloudinary.com/do3dbemlj/image/upload/v1664393564/news/Screen_Shot_2022-09-28_at_16.25.35_qwo0d9.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393573/news/Screen_Shot_2022-09-28_at_16.25.25_bqpteh.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393576/news/Screen_Shot_2022-09-28_at_16.24.56_xknaez.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393587/news/Screen_Shot_2022-09-28_at_16.25.06_liuaav.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393587/news/Screen_Shot_2022-09-28_at_16.25.14_fqbot8.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393587/news/Screen_Shot_2022-09-28_at_16.25.14_fqbot8.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393588/news/Screen_Shot_2022-09-28_at_16.24.46_r4qa8a.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393591/news/Screen_Shot_2022-09-28_at_16.24.37_szqvak.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393594/news/Screen_Shot_2022-09-28_at_16.24.19_oxy6un.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664393599/news/Screen_Shot_2022-09-28_at_16.24.27_so50eq.png"],
    shortDescription: "The house faces the Mediterranean, in a place where an imposing dune protects the coastline from storms. This starting point defines the configuration...",
    description: "The house faces the Mediterranean, in a place where an imposing dune protects the coastline from storms. This starting point defines the configuration of the project. The house materializes with two volumes arranged perpendicular to each other.</br>In order to have views of the sea, the program of uses of the house is inverted with respect to the traditional scheme, the day floor is arranged on the upper floor to be able to look over the level of the dune and takes advantage of the lower level roof as a gazebo. </br>The sleeping area is located on the access level, perpendicular to the sea. The circulation is arranged in the most public part of the plot open to the pool area, while the rooms open onto a beautiful consolidated garden with small species that existed in the place. The flight of the upper floor ends with a kind of cloister open from above that allows the main room to be illuminated from the south while maintaining privacy, and at the same time casts the necessary shade on the lower level. The staircase is drawn at the intersection of both volumes marking the access point of the house.</br> In short, two volumes adapted to enjoy the surrounding conditions, the views, the shade... nothing more, nothing less."
  },
  {
    id: "02",
    title: "CASA DEL SILENCIO",
    location: "Valencia",
    images: ["https://res.cloudinary.com/do3dbemlj/image/upload/v1664394905/news/Screen_Shot_2022-09-28_at_16.46.17_mh7gpp.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664394914/news/Screen_Shot_2022-09-28_at_16.46.09_s7xsef.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395042/news/Screen_Shot_2022-09-28_at_16.47.38_grnvcl.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395043/news/Screen_Shot_2022-09-28_at_16.46.58_kyev9m.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395044/news/Screen_Shot_2022-09-28_at_16.47.28_yhx42s.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395047/news/Screen_Shot_2022-09-28_at_16.47.47_dfp1dl.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395049/news/Screen_Shot_2022-09-28_at_16.47.19_dvlhul.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395050/news/Screen_Shot_2022-09-28_at_16.47.08_kvbj4k.png"],
    shortDescription: "The project consists of making a musician's studio coexist with his home. Located in a housing area near Valencia, where the neighboring houses are very close to each other...",
    description: "The project consists of making a musician's studio coexist with his home. Located in a housing area near Valencia, where the neighboring houses are very close to each other.</br>It is decided to generate a semi-buried volume on the ground floor that configures the recording studio.</br> A concrete enclosure, within another concrete enclosure, with highly studied acoustics. This volume divides the ground floor into the entrance hall and the public area of the house, open to the garden and pool. This level is materialized with natural cement mortars, in its gray materiality, both the exterior and the pavements and the pool.</br>On this level a floor is deposited with the night area materialized with white lime mortar. Apparently closed in front of the environment, but open in its fifth façade to its adjoining gardens. A kind of intimate patios where you can enjoy nature and silence."
  },
  {
    id: "03",
    title: "CASA DEL ACANTILADO",
    location: "CALPE, ALICANTE",
    images: ["https://res.cloudinary.com/do3dbemlj/image/upload/v1664395050/news/Screen_Shot_2022-09-28_at_16.47.08_kvbj4k.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395429/news/Screen_Shot_2022-09-28_at_16.59.27_r4edqc.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395439/news/Screen_Shot_2022-09-28_at_16.59.36_cfhqzs.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395439/news/Screen_Shot_2022-09-28_at_16.59.36_cfhqzs.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395446/news/Screen_Shot_2022-09-28_at_17.00.12_es65ra.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395449/news/Screen_Shot_2022-09-28_at_17.00.22_ri8usc.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395452/news/Screen_Shot_2022-09-28_at_17.00.02_ayf8st.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395452/news/Screen_Shot_2022-09-28_at_16.59.53_out2kt.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395453/news/Screen_Shot_2022-09-28_at_16.59.46_mgfmgy.png"],
    shortDescription: "We like that quality of architecture that makes it possible to build a house in the air, to walk on water. An abrupt site overlooking the sea...",
    description: "We like that quality of architecture that makes it possible to build a house in the air, to walk on water. An abrupt site overlooking the sea, it is best not to do anything, you want to stay. A piece is crimped that respects the natural profile of the terrain.</br>Above, the shadow, the house, looking serenely towards the Mediterranean Sea. Under the sun, the pool brings us closer to the sea, a quiet cove.</br>At the turning point, the staircase proposes a suggestive route, a garden in the basement...</br>Given the steep slope of the plot and the desire to develop the house on one floor. A three-dimensional structure of screens and reinforced concrete slabs is chosen that adapts to the topography, carrying out the minimum possible earthworks.</br>This monolithic structure anchored to the rock generates a horizontal platform, at the access level from the street, on which the house is located. The pool area is located at a lower level in an existing flat area on the plot. The concrete structure is thermally insulated on the outside, with a smooth, flexible, white lime stucco as a finish. The rest of the materials, walls, pavements, roof gravel...maintain the same color emphasizing the unitary character."
  },
  {
    id: "04",
    title: "CASA HOFMANN",
    location: "VALENCIA",
    images: ["https://res.cloudinary.com/do3dbemlj/image/upload/v1664395796/news/Screen_Shot_2022-09-28_at_17.08.29_fjkown.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395811/news/Screen_Shot_2022-09-28_at_17.09.37_nrfpbf.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395813/news/Screen_Shot_2022-09-28_at_17.09.11_nejufn.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395816/news/Screen_Shot_2022-09-28_at_17.09.24_g8yhzl.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395818/news/Screen_Shot_2022-09-28_at_17.09.02_kqwxtr.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395817/news/Screen_Shot_2022-09-28_at_17.08.41_c5xlyi.png", "https://res.cloudinary.com/do3dbemlj/image/upload/v1664395819/news/Screen_Shot_2022-09-28_at_17.08.54_qpi0ec.png"],
    shortDescription: "A landscape surrounded by consolidated gardens, an elevated and elongated plot with a distant view of the sea, and a pleasant breeze, constitute...",
    description: "A landscape surrounded by consolidated gardens, an elevated and elongated plot with a distant view of the sea, and a pleasant breeze, constitute the sought-after and fortunate starting point for this story.</br>Three elements make up the project by the Valencia Fran Silvestre Architects studio. An extruded roof in the longitudinal direction of the land in the shape of a T constitutes the structure under which the inhabited space is located. This geometry allows you to feel the sea while protecting yourself from the gaze of others, seeking the sensation of living without neighbors. Helps control the southern sun during the summer and lets it through in the winter. The walkable roof is transformed into a kind of belvedere that enjoys the entire surface of the plot.</br>A single free-standing piece of furniture houses the structure of the Hofmann House and distributes the spaces filtering privacy, opening possibilities in the way of circulating and using the space. The main room, under the cantilevered shadow, is arranged in continuity with the outside. The interior of the furniture includes the wet parts and delimits the scale of the night areas that fall to the quieter portion of the garden. The studio opens on the corner with the best views.</br>These two elements, cover and furniture, are deposited on the stone base in which the sheet of water and the rest of the uses of the house are excavated, giving rise to the third element. These spaces adapt to the natural unevenness that exists on the plot.</br>A project by Fran Silvestre Arquitecto Valencia."
  },

];
